# Generated by Django 5.2.5 on 2025-08-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_musictrack_videonews'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
